# Generated by Django 5.1.1 on 2024-09-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_parent_mlmodel_mlmodelstatus_parent_mlalgorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='code',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
